services:
  nextjs:
    build:
      dockerfile: docker/dev.Dockerfile
      context: .
    volumes:
      - ./:/app
    restart: unless-stopped
    ports:
      - 3000:3000
    depends_on:
      - postgres

  postgres:
    image: postgres
    volumes:
      - yy-postgres-dev:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=ordinary-dev
      - POSTGRES_PASSWORD=e2t6dm0f
      - POSTGRES_DB=yydb
    restart: unless-stopped

volumes:
  yy-postgres-dev:
