services:
    nextjs:
        build:
            dockerfile: docker/dev.Dockerfile
            context: .
        volumes:
            - ./lib:/app/lib:ro,z
            - ./next.config.js:/app/next.config.js:ro,z
            - ./prisma:/app/prisma:z
            - ./pages:/app/pages:ro,z
            - ./photos:/app/photos:z
            - ./public:/app/public:z
            - ./styles:/app/styles:ro,z
        restart: unless-stopped
        depends_on:
            - postgres
        environment:
            - DATABASE_URL=postgresql://ordinary-dev:e2t6dm0f@postgres:5432/yydb?schema=public

    postgres:
        image: postgres
        volumes:
            - yy-postgres-dev:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=ordinary-dev
            - POSTGRES_PASSWORD=e2t6dm0f
            - POSTGRES_DB=yydb
        restart: unless-stopped

    nginx:
        build:
            dockerfile: docker/nginx.Dockerfile
            context: .
        ports:
            - 3000:80
        volumes:
            - ./photos:/app/photos:z
        restart: unless-stopped
        depends_on:
            - nextjs

volumes:
    yy-postgres-dev:
