services:
  nextjs:
    build:
      dockerfile: docker/dev.Dockerfile
      context: .
    volumes:
      - ./:/app
    restart: unless-stopped
    depends_on:
      - postgres

  postgres:
    image: postgres
    volumes:
      - yy-postgres-dev:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=ordinary-dev
      - POSTGRES_PASSWORD=e2t6dm0f
      - POSTGRES_DB=yydb
    restart: unless-stopped
  
  router:
    build:
      dockerfile: docker/router.Dockerfile
      context: .
    volumes:
      - ./:/app
    restart: unless-stopped
    ports:
      - 3000:80
    depends_on:
      - nextjs
    environment:
      - NEXTJS_URL=http://nextjs:3000

volumes:
  yy-postgres-dev:
