services:
    nextjs:
        build:
            dockerfile: docker/prod.Dockerfile
            context: .
        volumes:
            - yy-photos:/app/photos
        restart: unless-stopped
        depends_on:
            - postgres
        environment:
            - DATABASE_URL=postgresql://ordinary-dev:e2t6dm0f@postgres:5432/yydb?schema=public

    postgres:
        image: postgres
        volumes:
            - yy-postgres-prod:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=ordinary-dev
            - POSTGRES_PASSWORD=e2t6dm0f
            - POSTGRES_DB=yydb
        restart: unless-stopped

    nginx:
        build:
            dockerfile: docker/nginx.Dockerfile
            context: .
        ports:
            - 3000:80
        volumes:
            - yy-photos:/app/photos:z
        restart: unless-stopped
        depends_on:
            - nextjs

volumes:
    yy-postgres-prod:
    yy-photos:
