name: Test build

on:
  pull_request:
    branches:
      - production

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Download dependencies
      run: npm install

    - name: Try to build
      run: npm run build
